GAME-99
Nepommuck/SusGameDTO pull request #6
Opened 2024-11-13 13:12 UTC by uqsz

2024-11-16 12:20 UTC, Nepommuck requested changes
Remember about `CHANGELOG.md`!

2024-11-18 13:25 UTC, Uiskam commented on src/main/kotlin/edu/agh/susgame/dto/socket/ClientSocketMessage.kt
> +    data class PlayerJoiningRequest(
czy to są na pewno requesty?
ja bym wywalił ten suffix bo `PlayerJoiningRequest` brzmi jakby ktoś wysyłał prośbę o dołączenie do lobby która ma zostać zaakceptowana.

2024-11-18 13:44 UTC, Uiskam commented on src/main/kotlin/edu/agh/susgame/dto/socket/ClientSocketMessage.kt
> +    data class PlayerJoiningRequest(
Chociaż wsm odpowiedniki serwerowe są takimi odpowiedziami więc to się nawet jakos zgrywa ale np z perspektywy gracza trzeciego dostanie on nagle `PlayerJoiningResponse` mimo, że nikdy nie wysłał requesta.

2024-11-18 13:44 UTC, Uiskam commented on src/main/kotlin/edu/agh/susgame/dto/socket/ClientSocketMessage.kt
> +    data class PlayerJoiningRequest(
Więc ja bym wywalił wszystkie suffixy `request` i `response`

2024-11-18 20:52 UTC, merged